name: gocardless/atlantis/tag
on:
  push:
    branches:
    - master
jobs:
  docker_tag:
    if: ${{ !contains('refs/heads//.*/', github.ref) }}
    runs-on: ubuntu-latest
    container:
      image: golang:1.14
      env:
        GOFLAGS: "-mod=vendor"
    steps:
    - uses: actions/checkout@v2
    - run: make build-service
#     # 'setup_remote_docker' was not transformed because there is no suitable equivalent in GitHub Actions
    - name: Build and tag
      run: |-
        if [ -n "${{ github.ref }}" ]; then
          docker build -t "runatlantis/atlantis:${{ github.ref }}" .
          docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
          docker push "runatlantis/atlantis:${{ github.ref }}"
        fi
